### ISSUE TITLE
Curriculum enrollment and tracking

### ISSUE THREAD

**Issue by devvspaces** [devvspaces/roadflow-web#6]
- [x] Users can enroll in a curriculum
- [x] User can see all their enrolled curriculums
- [x] User can see their progress for each curriculum
- [x] Users can know if a module is completed for each curriculum
