### ISSUE TITLE
User roadmap enrollment and tracking

### ISSUE THREAD

**Issue by devvspaces** [devvspaces/roadflow-web#9]
- [ ] Users can enroll in a roadmap
- [ ] Users can track roadmap progress (completed curriculums, pending, and percentage progress)
- [ ] Users can see how they are faring on a roadmap (scores)
